### ISSUE TITLE
Support Python3

### ISSUE THREAD

**Issue by jramapuram** [jingweiz/pytorch-dnc#6]
It should be possible to make it so that it works with python2 and python3.
Mainly just a bunch of `print "..."` --> `print("...")` changes usually.

**Comment by jingweiz** [comment]
Hey,
I think I always use ```print("...")``` throughout the repo. The ```raw_input()``` is only used during testing for step by step visualization.

**Comment by jingweiz** [comment]
Also I think it should just also run under ```python3```, it's just I never tested in ```python3``` :)

**Comment by jramapuram** [comment]
Will give it a shot when the other issue is resolved :)
